### ISSUE TITLE
Cryptic authentication failure

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/benefice#182] opened 2022-09-15 14:44 UTC
![IMG_20220914_171531_755.jpg](https://user-images.githubusercontent.com/12877905/190432403-78aa807e-7b01-468b-ade5-0a263d8b47f9.jpg)

We've seen Benefice fail in production with the following error on successful auth (checked Auth0 logs, both sign up and sign in were successful), which means potential customers are unable to actually use the service.
No service logs were printed related to that apart from a plain 500. I believe @puiterwijk did some research into that and it turns out that by default most logs are dropped, please comment with more details @puiterwijk and whether that is now addressed. If it's not addressed yet, then it should be addressed in a separate PR.

**Comment by puiterwijk** [comment] 2022-09-15 15:21
This has now been addressed by setting a log_level in deployments.

**Comment by puiterwijk** [comment] 2022-09-15 15:22
(Identical to #178)

**Comment by puiterwijk** [comment] 2022-09-15 15:30
Okay, so we got 5 more of these errors today.
The error message is: `error constructing request token: Failed to parse server response`.
This is still not quite useful, because the corresponding auth0 responses are all succesful.
Maybe we need to log more about which parts fails (getting userid, getting token, getting claims, etc).

**Comment by puiterwijk** [comment] 2022-09-19 14:27
This turned out to be caused by the auth0 not setting the has_starred_enarx claim to `false` if it was false, and the application crashing in this case.
This particular case is now fixed by making sure `has_starred_enarx` has a value.

It is still useful to get a better error page.

**Comment by definitelynobody** [comment] 2022-09-20 14:20
Closing this as it should be resolved. Created a follow up issue for the error page https://github.com/profianinc/benefice/issues/189

**Closed by definitelynobody** 2022-09-20 14:20 UTC
